### PR TITLE
Create Sec8MF_2019_04.sas

### PR DESCRIPTION
**Pull request by Woliver01**
@mcohenui let me know if this looks okay, I want to make sure the new operating system is working with SAS.

### CODE REVIEW

**Comment by mcohenui** [comment]
@Woliver01 Yes. Looks good to merge.

**Comment by Woliver01** [comment]
@mcohenui Please review MFIS and REAC.

**Comment by mcohenui** [comment]
@Woliver01 The Reac and Mfis programs need the date added to the program name in the header, but other than that they are good to merge.

**Comment by Woliver01** [comment]
@mcohenui Thanks, just added those. Going to merge and continue with the update.

**Pull request merged**
