### PR TITLE
Created MFIS for Dec Update

### PR DESCRIPTION
**Pull request by Woliver01**
@mcohenui With the MFIS data, I think there's an issue with a new/altered SOA code that may need to be changed in the make_formats program. I think I need to add a new category code (YHC) to the program, but let me know if I'm off track.

### CODE REVIEW

**Comment by mcohenui** [comment]
@Woliver01 Yes, it looks like you will need to edit the make_formats program.

**Comment by Woliver01** [comment]
@mcohenui Do you have the rm-t_11.30.2019 csv open? It won't let me open it and my log is saying it's in use.

**Comment by Woliver01** [comment]
@mcohenui Also, just added the REAC scores for review to keep things moving.

**Comment by mcohenui** [comment]
@Woliver01 Ok, so for the first MFIS warning, you need to add the YHC code to the formatting. I will email you the SoA list that has this code in it. For the other warnings, there just isnt a subcategory listed in the HUD data. We can ignore those warnings.

**Comment by Woliver01** [comment]
@mcohenui The YHC code warning is still showing up in the log. Do I need to create a new issue so I can pull it to the L drive?

**Comment by mcohenui** [comment]
@Woliver01 Yes, if you remember, the formatting is pulled from the L drive. So you need to update make_formats program in a new issue and run through that process before you would see the changes in the MFIS program

**Comment by mcohenui** [comment]
@Woliver01 Also, the REAC code looks good.

**Pull request merged**
