### PR TITLE
HUD 12/4/17 update

### PR DESCRIPTION
**Pull request by npstrayer**

### CODE REVIEW

**Comment by npstrayer** [comment]
@NeighborhoodInfoDC/review

**Comment by ptatian** [comment]
Hi @npstrayer. You said their was no MFIS update, but it seems like you created an MFIS program?

**Comment by npstrayer** [comment]
@ptatian I did not intend too. The program referenced here is from the October update. I'm not sure why github uploaded it to this issue.

**Comment by ptatian** [comment]
The program might have been in your folder for some reason. It's creating a conflict on the merge. If you would please delete the program file and push that as a commit, that may clear up the problem.

**Comment by ptatian** [comment]
@npstrayer I tested the Sec8 program but got an error message.

```
ERROR: Physical file does not exist, L:\Libraries\HUD\Raw\Sec8MF\2017-11\MF_Properties_with_Assistance___Sec8_Contracts.txt.
```

Did you try running the program before requesting the review?

**Comment by ptatian** [comment]
Hi @npstrayer. You reverted the commit that you made earlier (40e3fca). That commit had changes in addition to the MFIS program. It also included the Sec8 programs for Oct and Nov. By reverting the commit, you deleted those programs as well. 

Let me suggest the following steps to get back on track.
- Revert the reverted commit you just made (eee136f) to restore all of the programs. 
- Go into Windows Explorer and delete the program **Prog/MFIS/MFIS_2017_10.sas**. This will be recorded as a change in GitHub.
- Commit the change you just made (the deleted program). 

Please let me know if any of those steps don't make sense to you.

Once that is done, there is still the error in the **Prog/Sec8MF/Sec8MF_2017_11.sas** program, which I mentioned above, that needs to be resolved. Please see if you can fix it. If you get stuck, please don't spend a lot of time. Please ask me for help.

If you need a refresh on basic GitHub procedures, you may want to look at the [Hello, World! tutorial](https://guides.github.com/activities/hello-world/). 

Thanks, Noah. Please let me know if you have any questions.

**Comment by npstrayer** [comment]
Hi @ptatian,

Thank you for the help. I've gone ahead and made those changes, sorry about the confusion. I believe the branches can be merged now.

**Pull request merged**
