### PR TITLE
Update MFIS for 07/2016 and update Macro to cut out Premise_ID

### PR DESCRIPTION
**Pull request by katyaabaz**
Cut out premise_id by commenting out any steps involving premise_id and
copying in modified versions. @ptatian the Macro revision needs review!

### CODE REVIEW

**Comment by ptatian** [comment]
Taking a look now.

**Comment by ptatian** [comment]
It would be better to create a blank premise_id var in the file (char length 16) because that variable is referenced in the Preservation Catalog update programs. That way we should not need to modify the Catalog programs.

**Comment by ptatian** [comment]
Also, it would be preferred to make your macro changes contingent on the file date, so that the macro still works properly for older files. For example,

> %if &filedate >= '31jul2016'd %then %do;
> {input without premise_id};
> length premise_id $ 16;
> premise_id = '';
> %end;
> %else %do;
> {input with premise_id}
> %end;

**Comment by katyaabaz** [comment]
OK – thanks!

**Comment by katyaabaz** [comment]
@ptatian I updated the MFIS macro accordingly. Let me know if I missed anything!

**Comment by ptatian** [comment]
Looks good! Please go ahead and finalize. Thanks!

**Pull request merged**
