### PR TITLE
Febuary update

### PR DESCRIPTION
**Pull request by npstrayer**
@mcohenui

### CODE REVIEW

**Comment by npstrayer** [comment]
@ptatian

**Comment by ptatian** [comment]
Sorry, @npstrayer. Did you need a review? It would help if you could say in your message that you would like a review when you @-mention, just so it's clear.

**Comment by npstrayer** [comment]
Apologies, I should have mentioned that. Yes, I do need a review. Thanks!

**Comment by ptatian** [comment]
@npstrayer OK. I'll take a look.

**Pull request merged**
