### PR TITLE
Created Sec8MF for PresCat Update Nov 2020

### PR DESCRIPTION
**Pull request by Woliver01**
@mcohenui Please review.

### CODE REVIEW

**Comment by mcohenui** [comment]
@Woliver01 Please review the output from the program. Starting with the variable "mgmt_agent_indv_first_name", the data isn't aligned with the column headers. Likely, it is due to some change in the order of variables in the raw data file. I believe this happened last month as well, so it seems like we will need to alter the macro that reads in the raw data: Sec8MF_readbasetbls.sas

**Comment by Woliver01** [comment]
@mcohenui Hey Mychal, I'll take a look. I believe this has been the case for the past several updates, though, potentially since last year. At one point, I thought we just figured it was something that we could be okay with in terms of the update.

Also there's no MFIS update for October yet so I just moved on to the REAC portion of the update. I committed the REAC update but the dataset didn't have any data in it, so I tried converting the pdf file of the dataset into Excel but we Adobe app keeps crashing so I'm not really sure what to do. Do you think you could convert it (and let me know if that's a reasonable alternative)?

**Comment by mcohenui** [comment]
@Woliver01 Yea, it happened last month, and I think we ended up deciding to just make a copy of the raw file to use that had the right variable order. Given that it seems like it will be an ongoing issue, it is best to update the macro so that future updates won't have the same problem. Let me know if run into issues working on the macro.

I will take a look at the REAC update.

**Comment by Woliver01** [comment]
@mcohenui Here are some things I noticed:

New variables (variables that don't match the wording of the code in the macro):
"owner_company" (no "_type" at the end of code)
"mgmt_agent_company" (no "_type" at the end of code)
"primary_financing" (no "_type" at the end of code)
"property_category" (no "_name" at the end" of code)

Also   "mgmt_agent_company_type" which is supposed to come after "mgmt_agent_participant_id" and before "mgmt_agent_indv_first_name" doesn't match up with the dataset. 

Given these, I have a couple questions. 1) Is this a matter of rearranging the lines of code? Or is it about the changes in wording of the code? Or is it doing both, or something else entirely?

**Comment by mcohenui** [comment]
@Woliver01 Leave the variables that are in the right order, but the wording is off. The way SAS reads data is just in the order they appear in the raw data. The variable names don't need to match exactly. 

The real issue is where the variables are in the wrong order. Rearrange the code to match the raw data, and then test the Sec8MF update program again.

**Comment by Woliver01** [comment]
@mcohenui I just made changes to the macro. I realized that there were email variables on the raw data, so I just added in those lines of code to the macro. But there are still those a few of those "management_participant_id" warnings, although much less than before.

**Comment by mcohenui** [comment]
@Woliver01 Macro looks great to me, good job. Hopefully they don't change the format again next month...

In terms of the REAC, not sure what was happening. But I was able to download the excel from the HUD site, convert it to a .csv and the program ran fine. should be good to merge.

**Pull request merged**
