### PR TITLE
Develop #144

### PR DESCRIPTION
**Pull request by rpitingolo**
@lhendey can you please, review? A few things of note:

1. The output for each program is 1 big national file with tracts, counties and places all combined. It could be three separate files if you think that's better, but for the big national file I figured it was fine to keep it together and filter down as needed. 
2. The labels are truncated because the data dictionary has descriptions that exceed the character limit. If you think it's worth trying to shorten them I could try to do it via find/replace in Excel and update the macro, unless you think there is a better way.
3. The labels are hard-coded into a macro. I tried using proc SQL but it doesn't like when macro variables exceed 60k characters and no matter how I tried it kept breaking it because there are so many variables and long labels.

### CODE REVIEW

**Comment by lhendey** [comment]
@rpitingolo yes, i'm looking at it.

**Comment by lhendey** [comment]
@rpitingolo yes i'd like to shorten the labels if possible. the old programs looked like they had some examples of shortened labels. double check that the tables in the 2006-10 data and 2012-16 data are the same. 

there are uninitialized variables on the 2006-10 file.

**Comment by lhendey** [comment]
@rpitingolo also uninitialized vars on 2012-16. should there be estimates with zeros in them? (like t1_est218-236)?

**Comment by rpitingolo** [comment]
@lhendey thanks for the review, I'll double check on the 2006-10 data and clean up the labels.

**Comment by lhendey** [comment]
@rpitingolo any update on these?

**Comment by rpitingolo** [comment]
Working on it today. Will commit some changes later.

**Comment by rpitingolo** [comment]
@lhendey I fixed up the uninitialized variables and shortened the labels so they all fit now. I will check on the zero estimates next but have something else I need to get to first.

**Comment by rpitingolo** [comment]
@lhendey I spot checked some of the zero estimates against published ACS tables and confirmed that they are actually zeros (eg. tract 17031980000 actually has no occupied housing units so T1_est1=0 is right). 

Can you please re-review and then I can finalize?

**Comment by lhendey** [comment]
@rpitingolo - how is "shorten CHAS labels" fit in to the process? I can't run it by itself because there is no libname statement defining CHASraw.

**Comment by lhendey** [comment]
@rpitingolo 

shouldn't these be read in as character vars?

cnty      Num    8 BEST12. BEST32.                                                                                    
 place     Num    8 BEST12. BEST32.  Place FIPS. 5 digits. Included only at sum level 155 and 160.                     
  st        Num    8 BEST12. BEST32.  State FIPS. 2 digits.                                                             
sumlevel  Num    8 BEST12. BEST32.  Geographic summary level code.                                                    
tract     Num    8 BEST12. BEST32.  Tract FIPS. 6 digits. Only at sum level 140.

**Comment by rpitingolo** [comment]
@lhendey I added the libname statement to Shorten CHAS Labels.sas. The way that this works is that it takes the data dictionary file from the CHAS website (converted with stattransfer from xlsx) and shortens each of the label columns 1-5 for concatenating them together into a single label. Then it exports those labels as a CSV which I pasted into the %Label_CHAS macro. I tried to figure out a way to automate this but because of character limits on Proc SQL this is the best I could come up with. 

I think it's fine to leave cnty, place, st, and tract as numeric since they get converted into ucounty, uplace, and geo2010. I would even be in favor of dropping them from the national file in order to avoid confusion.

**Comment by lhendey** [comment]
@rpitingolo am i supposed to be able to run shorten CHAS labels independently? It can't resolve the &rawpath.

Please remove the numeric geographies.

**Comment by rpitingolo** [comment]
@lhendey realized I had a couple commits I hadn't pushed. You can run run shorten CHAS labels independently now. I also removed the numeric geographies. Let me know if this need another review or is OK  to finalize.

**Comment by lhendey** [comment]
@rpitingolo still can't run the short labels program independently.

**Comment by rpitingolo** [comment]
@lhendey try now.

**Comment by lhendey** [comment]
@rpitingolo okay to merge.

**Pull request merged**
