### PR TITLE
Create Sec8 for PresCat January 2021 update

### PR DESCRIPTION
**Pull request by Woliver01**
@mcohenui The warnings in the Sec 8 update are from a handful rows where the address was formatted incorrectly and spread across two additional columns. However, I don't believe that this affected the four states that we're using for the update. But let me know if I should make that change (and if it's something I need to do in SAS or in MS Access). Please review.

### CODE REVIEW

**Comment by mcohenui** [comment]
@Woliver01 good to merge

**Comment by Woliver01** [comment]
@mcohenui Hey Mychal. So there's still that issue with the SOA code for the MFIS program. I know we addressed it last time and I think we landed on the need for something to be changed in the macro? Additionally, the REAC log had an error that said that it couldn't find a file called: \reacphyinspecscorreldates.csv. We usually name the file mf_inspection_report so I'm wondering if that's changed and if I should rename it to the one named in the log?

**Comment by mcohenui** [comment]
@Woliver01 Yes, the MFIS warning has come up for the past view months. Perhaps put a quick 15 minute meeting for us to discuss next week. But it is not affecting the output so the MFIS program is ok to merge. The issue with the REAC is more confusing. If you open the macro REAC_read_update_file, there is a %if statement using the filedate (created to mark the date when the format changed). For some reason, it is running two of the if statements, even though they are mutually exclusive. @ptatian Do you mind taking a quick look?

**Comment by mcohenui** [comment]
DCData\Libraries\HUD\Macros\REAC_read_update_file.sas

**Comment by ptatian** [comment]
Thanks, @mcohenui and @Woliver01. %if conditions in macros behave differently than regular if's. In macros, some things don't resolve as you would expect. In this case, the macro processor doesn't know what things like `'06feb2019'd` mean. You need to force SAS to evaluate the expressions by enclosing then in a %sysevalf() function.

`%if %sysevalf( &filedate => '31oct2019'd ) %then %do;`

Try that for both %if's and see if it resolves the problem.

**Comment by Woliver01** [comment]
That resolved it, thanks @ptatian! @mcohenui do you want to take another look before I merge these programs?

**Comment by mcohenui** [comment]
@Woliver01 Good to merge

**Pull request merged**
